"""Offline continuation conversion for the legacy LTP 1.0 interchange document.

The source is retained exactly. One explicit root goal becomes a native goal;
legacy structures become labeled source-report notes, never executable graphs.
A deterministic proposal adapter goes through the ordinary retained-input and
publication use cases. It adds no import backdoor or inferred participant assent.
"""

import base64
from collections import Counter, defaultdict
from copy import deepcopy
from hashlib import sha256
import json
from pathlib import Path

import yaml

from reason_commons.bootstrap import create_case, open_case
from reason_commons.domain.model import require, shape, string_list, text


SECTIONS = ("entities", "designations", "relationships", "assumptions", "assessments", "changes")
QUESTION = "Which proposed next action should we work on now, and what result would show progress toward the existing goal?"
SOURCE_ATTRIBUTION = "Imported LTP document; individual authorship is not inferred"
LIMITATIONS = (
    "This is a continuation conversion of LTP 1.0, not a native graph import.",
    "The original root goal is a native goal. Its unrecorded measure, baseline, horizon, scope and safeguards stay unknown.",
    "All original entities, designations, relationships, assumptions and assessments are preserved as labeled source-report notes and in the exact source attachment.",
    "Causal, necessity, conflict, prerequisite, future-reality, transition and supersession meanings remain source claims in prose, without native executable graph semantics.",
    "Transition actions and prospective effects remain proposals. No bounded test, owner, completion, observation or agreement is inferred.",
    "Original IDs and provenance locators remain available. Locators do not establish that the referenced files are present or their line numbers still match.",
    "The imported source is historical; conversion does not verify its present-day accuracy or reconstruct past application revisions.",
    "The initial question is authored by the conversion adapter to resume work, not quoted from the source or generated by an LLM.",
)


class UniqueLoader(yaml.SafeLoader):
    """Reject ambiguous mappings instead of silently keeping the final key."""


def unique_mapping(loader, node):
    loader.flatten_mapping(node)
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node)
        require(isinstance(key, str) and key not in result, "Duplicate or non-text YAML key")
        result[key] = loader.construct_object(value_node)
    return result


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def read_ltp(content):
    require(isinstance(content, bytes) and len(content) <= 4 * 1024 * 1024, "Supply an LTP document up to 4 MiB")
    try:
        document = yaml.load(content.decode("utf-8"), Loader=UniqueLoader)
    except yaml.YAMLError:
        raise ValueError("Source is not valid YAML") from None
    shape(document, {"ltp"}, {"ltp"}, "LTP document")
    value = document["ltp"]
    fields = {"schema_version", "project_id", "title"} | set(SECTIONS)
    shape(value, fields, fields, "LTP 1.0 document")
    require(value["schema_version"] == "1.0", "Only LTP schema 1.0 is supported by this conversion")
    for key in ("title", "project_id"):
        text(value[key], key)
    indices, all_ids = {}, set()
    for section in SECTIONS:
        rows = value[section]
        require(isinstance(rows, list), f"{section} must be a list")
        indices[section] = {}
        for row in rows:
            require(isinstance(row, dict), f"{section} entries must be objects")
            text(row.get("id"), "legacy ID")
            require(row["id"] not in all_ids, "Legacy IDs must be unique")
            all_ids.add(row["id"])
            indices[section][row["id"]] = row
    require(value["changes"] == [], "Nonempty legacy change logs need a dedicated history mapping")
    for entity in value["entities"]:
        shape(entity, {"id", "tree", "statement", "provenance"}, {"id", "tree", "statement", "provenance"}, "entity")
        for key in ("tree", "statement"):
            text(entity[key], key)
        shape(entity["provenance"], {"path"}, {"path"}, "provenance")
        text(entity["provenance"]["path"], "provenance path")
    for designation in value["designations"]:
        shape(designation, {"id", "entity_id", "role", "parent_designation_id"}, {"id", "entity_id", "role"}, "designation")
        text(designation["role"], "role")
        text(designation["entity_id"], "designated entity")
        require(designation["entity_id"] in indices["entities"], "Dangling designated entity")
        if "parent_designation_id" in designation:
            text(designation["parent_designation_id"], "parent designation")
            require(designation["parent_designation_id"] in indices["designations"], "Dangling parent designation")
    for relation in value["relationships"]:
        shape(relation, {"id", "tree", "kind", "from_entity_ids", "to_entity_id"},
              {"id", "tree", "kind", "from_entity_ids", "to_entity_id"}, "relationship")
        text(relation["kind"], "relationship kind")
        text(relation["tree"], "relationship tree")
        text(relation["to_entity_id"], "conclusion entity")
        string_list(relation["from_entity_ids"], "premise entities")
        require(bool(relation["from_entity_ids"]), "Relationship requires premises")
        require(all(ref in indices["entities"] for ref in relation["from_entity_ids"] + [relation["to_entity_id"]]),
                "Dangling relationship entity")
    for assumption in value["assumptions"]:
        shape(assumption, {"id", "statement", "relationship_id"}, {"id", "statement", "relationship_id"}, "assumption")
        text(assumption["statement"], "assumption statement")
        text(assumption["relationship_id"], "assumption relationship")
        require(assumption["relationship_id"] in indices["relationships"], "Dangling assumption relationship")
    for assessment in value["assessments"]:
        shape(assessment, {"id", "kind", "tree", "statement", "subject_ids", "depends_on"},
              {"id", "kind", "tree", "statement", "subject_ids", "depends_on"}, "assessment")
        for key in ("kind", "tree", "statement"):
            text(assessment[key], key)
        for key in ("subject_ids", "depends_on"):
            string_list(assessment[key], key)
            require(all(ref in all_ids for ref in assessment[key]), "Dangling assessment dependency")
    roots = [d for d in value["designations"] if d["role"] == "goal" and "parent_designation_id" not in d]
    require(len(roots) == 1, "Conversion requires exactly one explicitly designated root goal")
    require(indices["entities"][roots[0]["entity_id"]]["tree"] == "goal", "Root goal must belong to the goal tree")
    return value


class ContinuationProposal:
    """A source-bound, one-use proposal generator; no model or extra commitments."""

    def __init__(self, value, source_ref, source_hash):
        self.value, self.source_ref, self.source_hash = deepcopy(value), source_ref, source_hash
        self.version = "ltp-continuation-conversion/1/source=" + source_hash
        self.mapping_keys = []
        self.calls = 0

    def propose(self, request):
        self.calls += 1
        require(self.calls == 1 and request["case"]["revision"] == 0 and not request["case"]["records"],
                "Conversion applies once to a fresh commons")
        source = request["sources"][self.source_ref]
        require(sha256(base64.b64decode(source["content_base64"], validate=True)).hexdigest() == self.source_hash,
                "Conversion source changed")
        # Cite the document for its claims. The request authorizes conversion;
        # it does not turn its sender into the author of every imported claim.
        refs = [self.source_ref]
        value = self.value
        root = next(d["entity_id"] for d in value["designations"] if d["role"] == "goal" and "parent_designation_id" not in d)
        entities = {e["id"]: e for e in value["entities"]}
        updates = []
        context = []

        def append(operation, data, key, alias):
            updates.append({"operation": operation, "temporary_id": alias, "data": data, "source_refs": refs[:]})
            self.mapping_keys.append(key)

        append("record_goal", {"statement": entities[root]["statement"], "scope": None, "horizon": None,
                               "measure": None, "baseline": None, "protections": []}, ("root_goal", root), "temp_root_goal")
        append("record_note", {"text": "Conversion scope and qualifications\n" + "\n".join(LIMITATIONS), "basis": "participant_report"},
               ("conversion", "scope"), "temp_conversion_scope")
        context += ["temp_root_goal", "temp_conversion_scope"]
        designations = defaultdict(list)
        incoming = defaultdict(list)
        for designation in value["designations"]:
            designations[designation["entity_id"]].append(designation)
        for relation in value["relationships"]:
            if relation["kind"] in {"supersedes", "challenges"}:
                incoming[relation["to_entity_id"]].append(relation)
        for index, entity in enumerate(value["entities"]):
            alias = f"temp_entity_{index}"
            parts = [f"LTP entity {entity['id']} ({entity['tree']})", entity["statement"],
                     "Original provenance: " + entity["provenance"]["path"]]
            for designation in designations[entity["id"]]:
                parent = designation.get("parent_designation_id")
                parts.append(f"Source designation {designation['id']}: {designation['role']}" +
                             (f"; parent designation {parent}" if parent else ""))
            for relation in incoming[entity["id"]]:
                parts.append(f"Historical qualification: source relationship {relation['id']} says " +
                             ", ".join(relation["from_entity_ids"]) + " " + relation["kind"] + " this statement. No new adjudication is added.")
            roles = {d["role"] for d in designations[entity["id"]]}
            if entity["tree"] == "future_reality" or "transition_expected_effect" in roles:
                parts.append("Prospective source claim; not an observed result.")
            if "transition_action" in roles:
                parts.append("Proposed source work; owner, execution and attained outcome are not established by this conversion.")
                context.append(alias)
            append("record_note", {"text": "\n".join(parts), "basis": "participant_report"}, ("entities", entity["id"]), alias)
        for index, relation in enumerate(value["relationships"]):
            content = (f"LTP relationship {relation['id']} ({relation['tree']}): {relation['kind']}\n"
                       "From entities (grouping retained): " + ", ".join(relation["from_entity_ids"]) +
                       "\nTo entity: " + relation["to_entity_id"] +
                       "\nReported source relationship; preserved as prose, without a native graph edge or independently verified causality.")
            append("record_note", {"text": content, "basis": "participant_report"},
                   ("relationships", relation["id"]), f"temp_relationship_{index}")
        for index, assumption in enumerate(value["assumptions"]):
            append("record_note", {"text": f"LTP assumption {assumption['id']} about relationship {assumption['relationship_id']}\n" +
                                   assumption["statement"] + "\nSource assumption; its truth is not established by conversion.",
                                   "basis": "participant_report"}, ("assumptions", assumption["id"]), f"temp_assumption_{index}")
        for index, assessment in enumerate(value["assessments"]):
            append("record_note", {"text": f"LTP assessment {assessment['id']} ({assessment['tree']}): {assessment['kind']}\n" +
                                   assessment["statement"] + "\nSubjects: " + ", ".join(assessment["subject_ids"]) +
                                   "\nDepends on: " + ", ".join(assessment["depends_on"]) +
                                   "\nReported source assessment, without newly inferred agreement or a native test review.",
                                   "basis": "participant_report"}, ("assessments", assessment["id"]), f"temp_assessment_{index}")
        return {"schema_version": "1", "delivery_profile": "p2", "request_id": request["input"]["request_id"],
                "base_revision": 0, "proposed_updates": updates,
                "intervention": {"kind": "question", "goal_ref": "temp_root_goal", "primary_prompt": QUESTION,
                                 "purpose": "Choose a next move in the imported, in-progress commons.",
                                 "rationale": "The source already has an overarching goal and proposed transition actions. Choose the next action and a prospective indication of progress while leaving unrecorded conditions unknown. This continuation question is authored by the conversion adapter.",
                                 "required_context_refs": context,
                                 "options": [{"id": "goal", "label": "Inspect the existing goal", "action": {"type": "view", "target": "goal"}},
                                             {"id": "source", "label": "Read the original reasoning and provenance", "action": {"type": "view", "target": "sources"}}]}}


def convert_ltp(source, destination, bundle, *, speaker, request_text):
    """Create a new native commons and portable bundle through public use cases."""
    source, destination, bundle = Path(source), Path(destination), Path(bundle)
    content = source.read_bytes()
    value = read_ltp(content)
    text(speaker, "declared importing participant")
    text(request_text, "literal conversion request")
    require(not destination.exists() and not bundle.exists(), "Conversion destinations must be new")
    require(bundle.suffix == ".reasoncase", "Use a .reasoncase bundle destination")
    source_hash = sha256(content).hexdigest()
    destination.parent.mkdir(parents=True, exist_ok=True)
    bundle.parent.mkdir(parents=True, exist_ok=True)
    with create_case(destination, value["title"]) as staging:
        source_ref = staging.add_source(source.name, content, SOURCE_ATTRIBUTION)
    converter = ContinuationProposal(value, source_ref, source_hash)
    with open_case(destination, consultant=converter) as app:
        result = app.submit(request_text, speaker, **app.workspace()["target"])
        require(result["status"] == "saved", "Conversion was not published; inspect retained input and receipt")
        case = app.inspect()["case"]
        records = [r for r in case["records"] if r["kind"] != "intervention"]
        require(len(records) == len(converter.mapping_keys), "Incomplete conversion mapping")
        mapping = {section: {} for section in SECTIONS}
        for (section, legacy_id), record in zip(converter.mapping_keys, records):
            if section in mapping:
                mapping[section][legacy_id] = record["ref"]
        for designation in value["designations"]:
            mapping["designations"][designation["id"]] = mapping["entities"][designation["entity_id"]]
        report = {"conversion_version": converter.version, "source_name": source.name, "source_sha256": source_hash,
                  "source_project_id": value["project_id"], "source_schema_version": "1.0", "source_ref": source_ref,
                  "case_id": case["case_id"], "case_revision": case["revision"], "request_id": result["request_id"],
                  "native_goal_ref": next(r["ref"] for r in records if r["kind"] == "goal"),
                  "counts": {section: len(value[section]) for section in SECTIONS},
                  "native_record_counts": dict(Counter(r["kind"] for r in case["records"])),
                  "limitations": list(LIMITATIONS), "legacy_to_native": mapping,
                  "initial_question": QUESTION, "model_inference_calls": 0}
        app.add_source("ltp-conversion-report.json", json.dumps(report, ensure_ascii=False, indent=2).encode("utf-8"),
                       "Deterministic conversion report; no participant endorsement inferred")
        before = app.inspect()
        app.export(str(bundle))
    with open_case(destination, writable=False) as resumed:
        require(resumed.inspect() == before, "Reopened conversion differs")
        original = resumed.sources()["sources"][source_ref]
        require(base64.b64decode(original["content_base64"], validate=True) == content, "Original source bytes differ")
    with open_case(bundle, writable=False) as portable:
        require(portable.inspect() == before, "Portable conversion differs")
        require(base64.b64decode(portable.sources()["sources"][source_ref]["content_base64"], validate=True) == content,
                "Portable source bytes differ")
    return report
