from typing import Protocol, List, Optional

from reason_commons.domain.model import Snapshot


class StoreError(OSError):
    """Durability or integrity could not be established."""


class WriterBusy(StoreError):
    pass


class ConsultantResponseError(ValueError):
    """Provider responded, but did not return a complete structured proposal."""


class CaseStore(Protocol):
    def current(self) -> Snapshot: ...
    def history(self) -> List[Snapshot]: ...
    def sources(self) -> dict: ...
    def retain(self, value: dict) -> None: ...
    def input(self, request_id: str) -> dict: ...
    def next_request_id(self) -> str: ...
    def next_revision(self) -> int: ...
    def reserved_counters(self) -> dict: ...
    def checkpoint(self, value: dict) -> None: ...
    def cursor(self) -> dict: ...
    def start_attempt(self, request_id: str) -> int: ...
    def received(self, request_id: str, attempt: int, proposal: dict, version: str) -> None: ...
    def pending_response(self, request_id: str) -> Optional[dict]: ...
    def receipt(self, request_id: str, attempt: int, value: dict) -> None: ...
    def attempts(self, request_id: str) -> List[dict]: ...
    def commit(self, snapshot: Snapshot, expected_revision: int) -> None: ...
    def confirm_durable(self) -> None: ...
    def add_source(self, name: str, content: bytes, speaker: str) -> str: ...
    def export(self, destination: str, cursor_override: Optional[dict] = None) -> None: ...
    def close(self) -> None: ...


class Consultant(Protocol):
    version: str

    def propose(self, request: dict) -> dict:
        """Return an untrusted structured proposal; application validates it."""
        ...


class Clock(Protocol):
    def now(self) -> str: ...


class CaseCapabilities(Protocol):
    """Shared semantic surface for local interfaces and skills.

    Every domain-significant local operation is expressible here. Presentation
    checkpoints and session lifecycle are separate; neither establishes domain
    truth. No repository or domain construction is exposed.
    """

    def inspect(self) -> dict: ...
    def history(self) -> dict: ...
    def workspace(self, view: str = "next", revision: Optional[int] = None,
                  selection: Optional[str] = None) -> dict: ...
    def sources(self) -> dict: ...
    def receipts(self, request_id: str) -> dict: ...
    def storage_help(self) -> str: ...
    def retain_input(self, text: str, speaker: str, base_revision: int,
                     response_target: Optional[str], intent: str = "answer",
                     declarations: Optional[dict] = None,
                     request_id: Optional[str] = None) -> dict: ...
    def consult(self, request_id: str) -> dict: ...
    def retry(self, request_id: str) -> dict: ...
    def submit(self, text: str, speaker: str, base_revision: int,
               response_target: Optional[str], intent: str = "answer",
               declarations: Optional[dict] = None,
               request_id: Optional[str] = None) -> dict: ...
    def accept(self, refs: List[str], speaker: str, base_revision: int, confirmed: bool = False) -> dict: ...
    def reject(self, refs: List[str], speaker: str, base_revision: int, confirmed: bool = False) -> dict: ...
    def undo(self, refs: List[str], speaker: str, base_revision: int, confirmed: bool = False) -> dict: ...
    def still_holds(self, ref: str, speaker: str, base_revision: int) -> dict: ...
    def set_acceptance(self, mode: str, speaker: str, base_revision: int) -> dict: ...
    def add_source(self, name: str, content: bytes, speaker: str) -> str: ...
    def export(self, destination: str) -> None: ...
