from typing import Protocol, List, Optional

from reason_commons.domain.model import Snapshot


class StoreError(OSError):
    """Durability or integrity could not be established."""


class WriterBusy(StoreError):
    pass


class CaseStore(Protocol):
    def current(self) -> Snapshot: ...
    def history(self) -> List[Snapshot]: ...
    def sources(self) -> dict: ...
    def retain(self, value: dict) -> None: ...
    def input(self, request_id: str) -> dict: ...
    def next_request_id(self) -> str: ...
    def next_revision(self) -> int: ...
    def reserved_counters(self) -> dict: ...
    def checkpoint(self, value: dict) -> None: ...
    def cursor(self) -> dict: ...
    def start_attempt(self, request_id: str) -> int: ...
    def received(self, request_id: str, attempt: int, proposal: dict, version: str) -> None: ...
    def pending_response(self, request_id: str) -> Optional[dict]: ...
    def receipt(self, request_id: str, attempt: int, value: dict) -> None: ...
    def attempts(self, request_id: str) -> List[dict]: ...
    def commit(self, snapshot: Snapshot, expected_revision: int) -> None: ...
    def add_source(self, name: str, content: bytes, speaker: str) -> str: ...
    def export(self, destination: str) -> None: ...
    def close(self) -> None: ...


class Consultant(Protocol):
    version: str

    def propose(self, request: dict) -> dict:
        """Return an untrusted structured proposal; application validates it."""
        ...


class Clock(Protocol):
    def now(self) -> str: ...


class CaseCapabilities(Protocol):
    """The minimal skill-facing surface. No repository or domain construction."""

    def inspect(self) -> dict: ...
    def retain_input(self, text: str, speaker: str, base_revision: int,
                     response_target: Optional[str], intent: str = "answer",
                     declarations: Optional[dict] = None,
                     request_id: Optional[str] = None) -> dict: ...
    def consult(self, request_id: str) -> dict: ...
    def retry(self, request_id: str) -> dict: ...

